name: Building

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: devkaduuu
      DOCKER_PASSWORD: dckr_pat_bVyWogEeFEB3Rvx8zX9zQTI8QHU
      REPOSITORY: study-api

    steps:
      - uses: actions/checkout@v3
      - name: docker login

        run: |
          docker login -u devkaduuu -p dckr_pat_bVyWogEeFEB3Rvx8zX9zQTI8QHU
      - name: build image
        run: docker build -t devkaduuu/study-api .
      - name: push to registry
        run: docker push devkaduuu/study-api
