# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - rm87385-studyapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_e3616c96072f4b9d82b6d51723531557 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5071583cc41f4ea9b751ddcba1b836d4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e3616c96072f4b9d82b6d51723531557 }}/study-api:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'rm87385-studyapi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_64a490711aac447a9c9986d6172607fb }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e3616c96072f4b9d82b6d51723531557 }}/study-api:${{ github.sha }}'